"""add category to bonus_scores

Revision ID: 1e4ee2f02eac
Revises: 3dccdf9c090d
Create Date: 2026-02-09 09:04:28.272180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e4ee2f02eac"
down_revision: Union[str, None] = "3dccdf9c090d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bonus_scores",
        sa.Column("category", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bonus_scores", "category")
    # ### end Alembic commands ###
