"""add given_by_name to bonus_scores

Revision ID: 3dccdf9c090d
Revises: a1b2c3d4e5f6
Create Date: 2026-02-09 02:06:53.020328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dccdf9c090d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_scores', sa.Column('given_by_name', sa.Text(), nullable=True))
    op.drop_constraint('facilitator_overrides_legacy_user_id_key', 'facilitator_overrides', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('facilitator_overrides_legacy_user_id_key', 'facilitator_overrides', ['legacy_user_id'])
    op.drop_column('bonus_scores', 'given_by_name')
    # ### end Alembic commands ###
