"""initial tables

Revision ID: 5c8d676613a9
Revises: 
Create Date: 2026-02-08 00:06:05.246176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8d676613a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cached_course_id', sa.BigInteger(), nullable=False),
    sa.Column('legacy_student_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('given_by_legacy_user_id', sa.BigInteger(), nullable=False),
    sa.Column('given_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_scores_cached_course_id'), 'bonus_scores', ['cached_course_id'], unique=False)
    op.create_index(op.f('ix_bonus_scores_legacy_student_id'), 'bonus_scores', ['legacy_student_id'], unique=False)
    op.create_table('cached_courses',
    sa.Column('legacy_course_id', sa.BigInteger(), nullable=False),
    sa.Column('legacy_user_group_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cohort', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('legacy_course_id')
    )
    op.create_table('cached_enrollments',
    sa.Column('legacy_user_id', sa.BigInteger(), nullable=False),
    sa.Column('legacy_course_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('legacy_user_id', 'legacy_course_id')
    )
    op.create_table('cached_users',
    sa.Column('legacy_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('legacy_user_id')
    )
    op.create_table('facilitator_favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_facilitator_id', sa.BigInteger(), nullable=False),
    sa.Column('cached_course_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilitator_favorites_legacy_facilitator_id'), 'facilitator_favorites', ['legacy_facilitator_id'], unique=False)
    op.create_table('quest_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('legacy_student_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('graded_by_legacy_user_id', sa.BigInteger(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_scores_legacy_student_id'), 'quest_scores', ['legacy_student_id'], unique=False)
    op.create_index(op.f('ix_quest_scores_quest_id'), 'quest_scores', ['quest_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cached_course_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_number', sa.Integer(), nullable=False),
    sa.Column('quest_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('quest_date', sa.Date(), nullable=False),
    sa.Column('created_by_legacy_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_cached_course_id'), 'quests', ['cached_course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quests_cached_course_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_quest_scores_quest_id'), table_name='quest_scores')
    op.drop_index(op.f('ix_quest_scores_legacy_student_id'), table_name='quest_scores')
    op.drop_table('quest_scores')
    op.drop_index(op.f('ix_facilitator_favorites_legacy_facilitator_id'), table_name='facilitator_favorites')
    op.drop_table('facilitator_favorites')
    op.drop_table('cached_users')
    op.drop_table('cached_enrollments')
    op.drop_table('cached_courses')
    op.drop_index(op.f('ix_bonus_scores_legacy_student_id'), table_name='bonus_scores')
    op.drop_index(op.f('ix_bonus_scores_cached_course_id'), table_name='bonus_scores')
    op.drop_table('bonus_scores')
    # ### end Alembic commands ###
